new_account = {
    'type': 'object',
    'properties': {
        'username': {'type': 'string',
            'pattern': '^\w{6,}$',
            'maxLength': 50,
	    'error_msg': 'Username must be at least 6 characters long and contain only alphanumerical characters and underscores',},
        'password': {'type': 'string',
            'pattern': '^[a-zA-Z0-9~!@#$%^&*]{9,}$',
            'maxLength': 50,
	    'error_msg': 'Password can only contain alphanumerical characters and ~!@#$%^&* and must be at least 9 characters long',},
        'email': {'type': 'string',
            'pattern': "^[a-zA-Z0-9!#$%&'*+-/=?^_`{|}~.]+@[a-zA-Z0-9-]+\.[a-zA-Z]+$",
            'maxLength': 100,
	    'error_msg': 'Invalid e-mail address',},
        'first_name': {'type': 'string',
            'pattern': '^[^\d~`!@#$%^&*()_+=<>,.?/:;"\[\]\\\{}|]+$',
            'maxLength': 100,
	    'error_msg': 'Invalid first name',},
        'last_name': {'type': 'string',
            'pattern': '^[^\d~`!@#$%^&*()_+=<>,.?/:;"\[\]\\\{}|]+$',
            'maxLength': 100,
	    'error_msg': 'Invalid last name',},
        'dob': {'type': 'string',
            'pattern': '^\d\d\d\d[/-]\d\d[/-]\d\d$',
	    'error_msg': 'Date of birth must be formatted as YYYY-MM-DD',},
        'sex': {'type': 'string',
            'pattern': '^male|Male|female|Female$',
	    'error_msg': 'Sex must be either "male" or "female"',},
        'phone': {'type': 'string',
            'pattern': '^\d{10,}$',
            'maxLength': 20,
	    'error_msg': 'Phone number can only contain digit characters',},
        'visible_in_directory': {'type': 'string',
            'pattern': '^y|Y|n|N$',
	    'error_msg': 'Visible in directory must be either "y" or "n"',},
        },
    'required': [
       'username',
       'password',
       'email',
       'first_name',
       'last_name',
       'dob',
       'sex',
       'phone',
       'visible_in_directory',
       ],
   }

update_account = {
    'type': 'object',
    'properties': {
        'username': {'type': 'string',
            'pattern': '^\w{6,}$',
            'maxLength': 50,
	    'error_msg': 'Username must be at least 6 characters long and contain only alphanumerical characters and underscores',},
        'password': {'type': 'string',
            'pattern': '^[a-zA-Z0-9~!@#$%^&*]{9,}$',
            'maxLength': 50,
	    'error_msg': 'Password can only contain alphanumerical characters and ~!@#$%^&* and must be at least 9 characters long',},
        'email': {'type': 'string',
            'pattern': "^[a-zA-Z0-9!#$%&'*+-/=?^_`{|}~.]+@[a-zA-Z0-9-]+\.[a-zA-Z]+$",
            'maxLength': 100,
	    'error_msg': 'Invalid e-mail address',},
        'first_name': {'type': 'string',
            'pattern': '^[^\d~`!@#$%^&*()_+=<>,.?/:;"\[\]\\\{}|]+$',
            'maxLength': 100,
	    'error_msg': 'Invalid first name',},
        'last_name': {'type': 'string',
            'pattern': '^[^\d~`!@#$%^&*()_+=<>,.?/:;"\[\]\\\{}|]+$',
            'maxLength': 100,
	    'error_msg': 'Invalid last name',},
        'dob': {'type': 'string',
            'pattern': '^\d\d\d\d[/-]\d\d[/-]\d\d$',
	    'error_msg': 'Date of birth must be formatted as YYYY-MM-DD',},
        'sex': {'type': 'string',
            'pattern': '^male|Male|female|Female$',
	    'error_msg': 'Sex must be either "male" or "female"',},
        'bio': {'type': 'string',
            'pattern': '^.*$',
            'maxLength': 500,
	    'error_msg': 'Bio cannot be more than 500 characters',},
        'picture': {'type': 'string',
            'pattern': '^.*$',
            'maxLength': 500,
	    'error_msg': 'Picture url cannot be more than 500 characters',},
        'phone': {'type': 'string',
            'pattern': '^\d{10,}$',
            'maxLength': 20,
	    'error_msg': 'Phone number can only contain digit characters',},
        'visible_in_directory': {'type': 'string',
            'pattern': '^y|Y|n|N$',
	    'error_msg': 'Visible in directory must be either "y" or "n"',},
        },
   }

join_team = {
    'type': 'object',
    'properties': {
        'league': {'type': 'string',
            'pattern': '\d+',
            'maxLength': 6,
	    'error_msg': 'League id can only contain numbers',},
        'team': {'type': 'string',
            'pattern': 'random|\d+',
            'maxLength': 6,
	    'error_msg': 'Team id can only contain numbers',},
        'team_password': {'type': 'string',
            'pattern': '^[a-zA-Z0-9~!@#$%^&*]{6,}$',
            'maxLength': 50,
	    'error_msg': 'Password can only contain alphanumerical characters and ~!@#$%^&* and must be at least 6 characters long',},
        },
    'required': [
       'league',
       'team',
       ],
   }
